package gal.uvigo.taskmanager

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import androidx.databinding.BaseObservable


@Parcelize
data class Task(
    // local stable id for UI/RecyclerView
    var localId: Long = 0,
    // remote id generated by server (CRUD CRUD)
    var _id: String? = null,
    var title: String = "",
    var description: String = "",
    var dueDate: String = "",
    var category: Category = Category.OTHER,
    var isDone: Boolean = false,
    var syncState: SyncState  = SyncState.SYNCED
) : Parcelable, BaseObservable()
